export default [
  {
    id: 1,
    name: 'Auto Speed',
    distance: 1,
    recent: false,
    status: 'proposal',
    zip: '43210',
    state: 'CA',
    logo: 'https://raw.githubusercontent.com/pigment/fake-logos/gh-pages/src/logos/color/auto-speed.svg',
  },
  {
    id: 2,
    name: 'Baby Swim',
    distance: 10,
    recent: false,
    status: 'underwriting',
    zip: '67890',
    state: 'CA',
    logo: 'https://raw.githubusercontent.com/pigment/fake-logos/gh-pages/src/logos/color/baby-swim.svg',
  },
  {
    id: 3,
    name: 'Fast Nav',
    distance: 10,
    recent: true,
    status: 'enrolling',
    zip: '23456',
    state: 'TX',
    logo: 'https://raw.githubusercontent.com/pigment/fake-logos/gh-pages/src/logos/color/fast-banana.svg',
  },
  {
    id: 4,
    name: 'James & Sons',
    distance: 10,
    recent: false,
    status: 'proposal',
    zip: '78901',
    state: 'FL',
    logo: 'https://raw.githubusercontent.com/pigment/fake-logos/gh-pages/src/logos/color/james-and-sons.svg',
  },
  {
    id: 5,
    name: "Pete's Blinds",
    distance: 10,
    recent: true,
    status: 'underwriting',
    zip: '90123',
    state: 'MI',
    logo: 'https://raw.githubusercontent.com/pigment/fake-logos/gh-pages/src/logos/color/petes-blinds.svg',
  },
  {
    id: 6,
    name: 'Space Cube',
    distance: 10,
    recent: true,
    status: 'enrolling',
    zip: '89012',
    state: 'MI',
    logo: 'https://raw.githubusercontent.com/pigment/fake-logos/gh-pages/src/logos/color/space-cube.svg',
  },
  {
    id: 7,
    name: 'Dance Studio',
    distance: 10,
    recent: false,
    status: 'proposal',
    zip: '89012',
    state: 'PA',
    logo: 'https://raw.githubusercontent.com/pigment/fake-logos/gh-pages/src/logos/color/the-dance-studio.svg',
  },
  {
    id: 8,
    name: 'Web Works',
    distance: 10,
    recent: true,
    status: 'underwriting',
    zip: '21098',
    state: 'CO',
    logo: 'https://raw.githubusercontent.com/pigment/fake-logos/gh-pages/src/logos/color/the-web-works.svg',
  },
];
